# Generated by Django 4.1.4 on 2023-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to='citiesapp/photos'),
        ),
        migrations.AlterField(
            model_name='city',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
