# Generated by Django 4.1.4 on 2023-01-10 21:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0002_alter_city_image_alter_city_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
